### ISSUE TITLE
Windows sign in

### ISSUE THREAD

**Issue by bachoo786** [sleevezipper/hass-workstation-service#143]
Hello there @sleevezipper 

Thanks for all your hard work on this :)

Just a quick question and I know its something that might breach the security etc but is it possible for a user to automatically login in to a Windows Laptop/Desktop using their password(s) from home assistant?

A good example for people working from would be; in the morning as the office door opens the computer turns on and logs you in automatically whilst your coffee is brewing. 

Something along those lines?

Thanks.

**Comment by sleevezipper** [comment]
Hi! 

I don't think it's possible interact with the login screen (also, the service won't be running if the user hasn't signed in since last boot). 

Also, if this could be implemented, it would delegate a lot of responsibility to HASS Workstation Service and I don't think it is mature enough for that yet. I hope you can find another way!
