### ISSUE TITLE
Contribution/Getting Started Document

### ISSUE THREAD

**Issue by ChrisMancini** [sleevezipper/hass-workstation-service#15]
Hi,

I was about to write something similar to this and saw your post on reddit and thought I could help contribute. Is there a document available that provides a list of necessary software, contribution guidelines, etc..?

I think VS2019, and/or VS Code with some extensions would provide the best experience as long as .Net 5 is installed.

I have the project downloaded, however, I am not able to run the service/UI without it crashing after attempting to add an existing sensor. 

I will continue to poke at it, but if you have something written up it would be helpful. Thanks!

**Comment by sleevezipper** [comment]
Hi! 

Awesome that you want to contribute! There definitely should be a developer readme of some sort as there are a few quirks.

First one: Make sure you start both projects when debugging. Right-click the solution > Properties > Startup projects > Multiple startup projects > Select start for both.

The frontend crashes if the service doesn't respond because there is no error handling.
